### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by guchengxi1994** [yanshouwang/opencv#1]
打包的时候，会把opencv_worldxxxd.dll 和其它东西一起打包进去，但是手动删除之后其实是可以运行的。我没有接触过c++和CMAKEList这些东西，请问是不是可以通过优化cmakelist脚本达到debug和release模式下使用不同的dll？

**Comment by yanshouwang** [comment]
> 打包的时候，会把opencv_worldxxxd.dll 和其它东西一起打包进去，但是手动删除之后其实是可以运行的。我没有接触过c++和CMAKEList这些东西，请问是不是可以通过优化cmakelist脚本达到debug和release模式下使用不同的dll？

现在就是这样的，在 release 模式下使用的是 opencv_wordxxx.dll，在 debug 模式下用的是 opencv_worldxxxd.dll，具体可以参考 windows 文件夹下的 [CMakeLists.txt](https://github.com/yanshouwang/opencv/blob/master/windows/CMakeLists.txt)

**Comment by guchengxi1994** [comment]
好的谢谢
